### PR TITLE
network byte order

### PR DESCRIPTION
**Pull request by peter-kutak**
network packets uses big-endian

### CODE REVIEW

**Comment by malbers15** [comment]
@peter-kutak can you explain this change a little bit or tie it to a logged issue where it is explained?  I was trying to review the code changes but there were no comments

**Comment by peter-kutak** [comment]
Hi,
IP packets uses big-endian encoding in general.
This change is not critical(interesting) because, here identifier and sequence number is used just to pair response with request. I swap it just for consistency.

I am fully satisfied with change in my own fork. Please, take this pull request for information only.

Thanks for your work

Peter

**Comment by malbers15** [comment]
Hi @peter-kutak ,

I can see what you mean after reviewing
https://www.sciencedirect.com/topics/computer-science/network-byte-order
and what it says about network byte order:
> To account for this possibility, the network byte order (which happens to be big-endian) is used by convention to send network data in a manner that will be received coherently, regardless of the endianness of the sender and receiver.

I have 2 more questions now:
1) can you leave some comments in the code explaining your changes so we can understand later when we forget this PR? :-)
2) can you elaborate on the python side code change?  Just the icmp.py changes: the syntax, etc.

**Comment by malbers15** [comment]
hi @peter-kutak , hoping you can follow up to the comments above when you get a chance

**Comment by alessandromaggio** [comment]
Changes are not clear and not well documened, this has been stale for a while. I understand the concept that network packets tend to be big endian, however I struggle to follow how this PR is implementing it properly and there are no comment to this. I will close this has it has been stale for almost two years, but feel free to reopen if you can provide more documentation.

**Pull request closed without merging**
